// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebQLNhanSu.Data;

#nullable disable

namespace WebQLNhanSu.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260326133223_InitIdentity")]
    partial class InitIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WebQLNhanSu.Models.BangLuong", b =>
                {
                    b.Property<int>("MaBangLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBangLuong"));

                    b.Property<decimal>("KhauTru")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LuongCoBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.Property<decimal>("Thuong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongLuong")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("[LuongCoBan] + [Thuong] - [KhauTru]");

                    b.HasKey("MaBangLuong");

                    b.HasIndex("MaNhanVien", "Thang", "Nam")
                        .IsUnique();

                    b.ToTable("BangLuongs", t =>
                        {
                            t.HasCheckConstraint("CK_BL_Nam", "[Nam] >= 2000");

                            t.HasCheckConstraint("CK_BL_Thang", "[Thang] BETWEEN 1 AND 12");

                            t.HasCheckConstraint("CK_BL_Tien", "[LuongCoBan] >= 0 AND [Thuong] >= 0 AND [KhauTru] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            MaBangLuong = 1,
                            KhauTru = 500000m,
                            LuongCoBan = 5000000m,
                            MaNhanVien = 1,
                            Nam = 2024,
                            Thang = 6,
                            Thuong = 1000000m,
                            TongLuong = 0m
                        },
                        new
                        {
                            MaBangLuong = 2,
                            KhauTru = 800000m,
                            LuongCoBan = 8000000m,
                            MaNhanVien = 2,
                            Nam = 2024,
                            Thang = 6,
                            Thuong = 1500000m,
                            TongLuong = 0m
                        },
                        new
                        {
                            MaBangLuong = 3,
                            KhauTru = 2000000m,
                            LuongCoBan = 15000000m,
                            MaNhanVien = 3,
                            Nam = 2024,
                            Thang = 6,
                            Thuong = 3000000m,
                            TongLuong = 0m
                        },
                        new
                        {
                            MaBangLuong = 4,
                            KhauTru = 200000m,
                            LuongCoBan = 3000000m,
                            MaNhanVien = 4,
                            Nam = 2024,
                            Thang = 6,
                            Thuong = 500000m,
                            TongLuong = 0m
                        },
                        new
                        {
                            MaBangLuong = 5,
                            KhauTru = 600000m,
                            LuongCoBan = 5000000m,
                            MaNhanVien = 1,
                            Nam = 2024,
                            Thang = 7,
                            Thuong = 1200000m,
                            TongLuong = 0m
                        });
                });

            modelBuilder.Entity("WebQLNhanSu.Models.CaLamViec", b =>
                {
                    b.Property<int>("MaCa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCa"));

                    b.Property<TimeSpan>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<string>("TenCa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaCa");

                    b.ToTable("CaLamViecs", t =>
                        {
                            t.HasCheckConstraint("CK_CaLamViec_Gio", "[GioKetThuc] > [GioBatDau]");
                        });

                    b.HasData(
                        new
                        {
                            MaCa = 1,
                            GioBatDau = new TimeSpan(0, 8, 0, 0, 0),
                            GioKetThuc = new TimeSpan(0, 16, 0, 0, 0),
                            TenCa = "Ca Sáng"
                        },
                        new
                        {
                            MaCa = 2,
                            GioBatDau = new TimeSpan(0, 16, 0, 0, 0),
                            GioKetThuc = new TimeSpan(0, 21, 0, 0, 0),
                            TenCa = "Ca Chiều"
                        },
                        new
                        {
                            MaCa = 3,
                            GioBatDau = new TimeSpan(0, 0, 0, 0, 0),
                            GioKetThuc = new TimeSpan(0, 8, 0, 0, 0),
                            TenCa = "Ca Đêm"
                        },
                        new
                        {
                            MaCa = 4,
                            GioBatDau = new TimeSpan(0, 8, 0, 0, 0),
                            GioKetThuc = new TimeSpan(0, 17, 0, 0, 0),
                            TenCa = "Ca Hành Chính"
                        },
                        new
                        {
                            MaCa = 5,
                            GioBatDau = new TimeSpan(0, 7, 0, 0, 0),
                            GioKetThuc = new TimeSpan(0, 19, 0, 0, 0),
                            TenCa = "Ca Linh Hoạt"
                        });
                });

            modelBuilder.Entity("WebQLNhanSu.Models.CauHinhLuong", b =>
                {
                    b.Property<int>("MaCauHinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCauHinh"));

                    b.Property<double>("HeSoTangCa")
                        .HasColumnType("float");

                    b.Property<decimal>("LuongCoBanMacDinh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PhuCap")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaCauHinh");

                    b.ToTable("CauHinhLuongs");

                    b.HasData(
                        new
                        {
                            MaCauHinh = 1,
                            HeSoTangCa = 2.2000000000000002,
                            LuongCoBanMacDinh = 100000m,
                            PhuCap = 50000m
                        },
                        new
                        {
                            MaCauHinh = 2,
                            HeSoTangCa = 1.3,
                            LuongCoBanMacDinh = 200000m,
                            PhuCap = 100000m
                        },
                        new
                        {
                            MaCauHinh = 3,
                            HeSoTangCa = 1.3999999999999999,
                            LuongCoBanMacDinh = 300000m,
                            PhuCap = 150000m
                        },
                        new
                        {
                            MaCauHinh = 4,
                            HeSoTangCa = 2.5,
                            LuongCoBanMacDinh = 400000m,
                            PhuCap = 200000m
                        });
                });

            modelBuilder.Entity("WebQLNhanSu.Models.ChamCong", b =>
                {
                    b.Property<int>("MaChamCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChamCong"));

                    b.Property<TimeSpan?>("GioRa")
                        .HasColumnType("time");

                    b.Property<double>("GioTangCa")
                        .HasColumnType("float");

                    b.Property<TimeSpan?>("GioVao")
                        .HasColumnType("time");

                    b.Property<int>("MaCa")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLam")
                        .HasColumnType("datetime2");

                    b.Property<double>("SoGioLam")
                        .HasColumnType("float");

                    b.HasKey("MaChamCong");

                    b.HasIndex("MaCa");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("ChamCongs", t =>
                        {
                            t.HasCheckConstraint("CK_ChamCong_Gio", "[SoGioLam] >= 0");

                            t.HasCheckConstraint("CK_ChamCong_OT", "[GioTangCa] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            MaChamCong = 1,
                            GioTangCa = 2.0,
                            MaCa = 1,
                            MaNhanVien = 1,
                            NgayLam = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoGioLam = 8.0
                        },
                        new
                        {
                            MaChamCong = 2,
                            GioTangCa = 0.0,
                            MaCa = 2,
                            MaNhanVien = 2,
                            NgayLam = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoGioLam = 8.0
                        },
                        new
                        {
                            MaChamCong = 3,
                            GioTangCa = 1.0,
                            MaCa = 3,
                            MaNhanVien = 3,
                            NgayLam = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoGioLam = 8.0
                        },
                        new
                        {
                            MaChamCong = 4,
                            GioTangCa = 0.0,
                            MaCa = 4,
                            MaNhanVien = 4,
                            NgayLam = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoGioLam = 8.0
                        });
                });

            modelBuilder.Entity("WebQLNhanSu.Models.ChucVu", b =>
                {
                    b.Property<int>("MaChucVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChucVu"));

                    b.Property<decimal>("LuongCoBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaChucVu");

                    b.HasIndex("TenChucVu")
                        .IsUnique();

                    b.ToTable("ChucVus", t =>
                        {
                            t.HasCheckConstraint("CK_ChucVu_Luong", "[LuongCoBan] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            MaChucVu = 1,
                            LuongCoBan = 5000000m,
                            TenChucVu = "Nhân Viên"
                        },
                        new
                        {
                            MaChucVu = 2,
                            LuongCoBan = 8000000m,
                            TenChucVu = "Trưởng Phòng"
                        },
                        new
                        {
                            MaChucVu = 3,
                            LuongCoBan = 15000000m,
                            TenChucVu = "Giám Đốc"
                        },
                        new
                        {
                            MaChucVu = 4,
                            LuongCoBan = 3000000m,
                            TenChucVu = "Thực Tập Sinh"
                        },
                        new
                        {
                            MaChucVu = 5,
                            LuongCoBan = 12000000m,
                            TenChucVu = "Phó Giám Đốc"
                        });
                });

            modelBuilder.Entity("WebQLNhanSu.Models.HopDong", b =>
                {
                    b.Property<int>("MaHopDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHopDong"));

                    b.Property<decimal>("Luong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaLoaiHopDong")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Đang hiệu lực");

                    b.HasKey("MaHopDong");

                    b.HasIndex("MaLoaiHopDong");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("HopDongs", t =>
                        {
                            t.HasCheckConstraint("CK_HopDong_Ngay", "[NgayKetThuc] IS NULL OR [NgayKetThuc] >= [NgayBatDau]");
                        });

                    b.HasData(
                        new
                        {
                            MaHopDong = 1,
                            Luong = 0m,
                            MaLoaiHopDong = 2,
                            MaNhanVien = 1,
                            NgayBatDau = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = "Đang hiệu lực"
                        },
                        new
                        {
                            MaHopDong = 2,
                            Luong = 0m,
                            MaLoaiHopDong = 2,
                            MaNhanVien = 2,
                            NgayBatDau = new DateTime(2021, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = "Đang hiệu lực"
                        },
                        new
                        {
                            MaHopDong = 3,
                            Luong = 0m,
                            MaLoaiHopDong = 2,
                            MaNhanVien = 3,
                            NgayBatDau = new DateTime(2019, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = "Đang hiệu lực"
                        },
                        new
                        {
                            MaHopDong = 4,
                            Luong = 0m,
                            MaLoaiHopDong = 1,
                            MaNhanVien = 4,
                            NgayBatDau = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = "Đang hiệu lực"
                        });
                });

            modelBuilder.Entity("WebQLNhanSu.Models.LichSuNguoiDung", b =>
                {
                    b.Property<int>("MaLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichSu"));

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("MaLichSu");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("LichSuNguoiDungs");

                    b.HasData(
                        new
                        {
                            MaLichSu = 1,
                            HanhDong = "Đăng nhập",
                            MaTaiKhoan = 3,
                            ThoiGian = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaLichSu = 2,
                            HanhDong = "Đăng nhập",
                            MaTaiKhoan = 3,
                            ThoiGian = new DateTime(2024, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaLichSu = 3,
                            HanhDong = "Đăng nhập",
                            MaTaiKhoan = 3,
                            ThoiGian = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaLichSu = 4,
                            HanhDong = "Tạo hợp đồng cho Nguyễn Văn A",
                            MaTaiKhoan = 1,
                            ThoiGian = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaLichSu = 5,
                            HanhDong = "Duyệt nghỉ phép cho Trần Thị B",
                            MaTaiKhoan = 2,
                            ThoiGian = new DateTime(2024, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaLichSu = 6,
                            HanhDong = "Cập nhật chấm công cho Lê Văn C",
                            MaTaiKhoan = 2,
                            ThoiGian = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("WebQLNhanSu.Models.LoaiHopDong", b =>
                {
                    b.Property<int>("MaLoaiHopDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiHopDong"));

                    b.Property<string>("TenLoaiHopDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaLoaiHopDong");

                    b.HasIndex("TenLoaiHopDong")
                        .IsUnique();

                    b.ToTable("LoaiHopDongs");

                    b.HasData(
                        new
                        {
                            MaLoaiHopDong = 1,
                            TenLoaiHopDong = "Hợp Đồng Thử Việc"
                        },
                        new
                        {
                            MaLoaiHopDong = 2,
                            TenLoaiHopDong = "Hợp Đồng Chính Thức"
                        },
                        new
                        {
                            MaLoaiHopDong = 3,
                            TenLoaiHopDong = "Hợp Đồng Thời Vụ"
                        },
                        new
                        {
                            MaLoaiHopDong = 4,
                            TenLoaiHopDong = "Hợp Đồng Cộng Tác Viên"
                        },
                        new
                        {
                            MaLoaiHopDong = 5,
                            TenLoaiHopDong = "Hợp Đồng Thực Tập"
                        });
                });

            modelBuilder.Entity("WebQLNhanSu.Models.NghiPhep", b =>
                {
                    b.Property<int>("MaNghiPhep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNghiPhep"));

                    b.Property<DateTime>("DenNgay")
                        .HasColumnType("datetime2");

                    b.Property<string>("LyDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Chờ duyệt");

                    b.Property<DateTime>("TuNgay")
                        .HasColumnType("datetime2");

                    b.HasKey("MaNghiPhep");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("NghiPheps", t =>
                        {
                            t.HasCheckConstraint("CK_NghiPhep_Ngay", "[DenNgay] >= [TuNgay]");
                        });

                    b.HasData(
                        new
                        {
                            MaNghiPhep = 1,
                            DenNgay = new DateTime(2024, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LyDo = "Đi du lịch",
                            MaNhanVien = 1,
                            TrangThai = "Chờ duyệt",
                            TuNgay = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaNghiPhep = 2,
                            DenNgay = new DateTime(2024, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LyDo = "Thăm gia đình",
                            MaNhanVien = 2,
                            TrangThai = "Chờ duyệt",
                            TuNgay = new DateTime(2024, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaNghiPhep = 3,
                            DenNgay = new DateTime(2024, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LyDo = "Đi công tác",
                            MaNhanVien = 3,
                            TrangThai = "Chờ duyệt",
                            TuNgay = new DateTime(2024, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaNghiPhep = 4,
                            DenNgay = new DateTime(2024, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LyDo = "Đi học",
                            MaNhanVien = 4,
                            TrangThai = "Chờ duyệt",
                            TuNgay = new DateTime(2024, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("WebQLNhanSu.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhanVien"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaChucVu")
                        .HasColumnType("int");

                    b.Property<int>("MaPhongBan")
                        .HasColumnType("int");

                    b.Property<int?>("MaTrinhDo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("MaChucVu");

                    b.HasIndex("MaPhongBan");

                    b.HasIndex("MaTrinhDo");

                    b.HasIndex("SoDienThoai")
                        .IsUnique()
                        .HasFilter("[SoDienThoai] IS NOT NULL");

                    b.ToTable("NhanViens", t =>
                        {
                            t.HasCheckConstraint("CK_NV_GioiTinh", "[GioiTinh] IN (N'Nam', N'Nữ', N'Khác')");
                        });

                    b.HasData(
                        new
                        {
                            MaNhanVien = 1,
                            DiaChi = "Hà Nội",
                            GioiTinh = "Nam",
                            MaChucVu = 1,
                            MaPhongBan = 1,
                            MaTrinhDo = 2,
                            NgaySinh = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0123456789",
                            TenNhanVien = "Nguyễn Văn A"
                        },
                        new
                        {
                            MaNhanVien = 2,
                            DiaChi = "Hồ Chí Minh",
                            GioiTinh = "Nữ",
                            MaChucVu = 2,
                            MaPhongBan = 2,
                            MaTrinhDo = 3,
                            NgaySinh = new DateTime(1992, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0987654321",
                            TenNhanVien = "Trần Thị B"
                        },
                        new
                        {
                            MaNhanVien = 3,
                            DiaChi = "Đà Nẵng",
                            GioiTinh = "Nam",
                            MaChucVu = 3,
                            MaPhongBan = 3,
                            MaTrinhDo = 4,
                            NgaySinh = new DateTime(1985, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0112233445",
                            TenNhanVien = "Lê Văn C"
                        },
                        new
                        {
                            MaNhanVien = 4,
                            DiaChi = "Hải Phòng",
                            GioiTinh = "Nữ",
                            MaChucVu = 4,
                            MaPhongBan = 4,
                            MaTrinhDo = 1,
                            NgaySinh = new DateTime(1995, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0223344556",
                            TenNhanVien = "Phạm Thị D"
                        });
                });

            modelBuilder.Entity("WebQLNhanSu.Models.PhongBan", b =>
                {
                    b.Property<int>("MaPhongBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhongBan"));

                    b.Property<string>("TenPhongBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaPhongBan");

                    b.HasIndex("TenPhongBan")
                        .IsUnique();

                    b.ToTable("PhongBans");

                    b.HasData(
                        new
                        {
                            MaPhongBan = 1,
                            TenPhongBan = "Phòng Nhân Sự"
                        },
                        new
                        {
                            MaPhongBan = 2,
                            TenPhongBan = "Phòng Kỹ Thuật"
                        },
                        new
                        {
                            MaPhongBan = 3,
                            TenPhongBan = "Phòng Kinh Doanh"
                        },
                        new
                        {
                            MaPhongBan = 4,
                            TenPhongBan = "Phòng Tài Chính"
                        },
                        new
                        {
                            MaPhongBan = 5,
                            TenPhongBan = "Phòng Marketing"
                        },
                        new
                        {
                            MaPhongBan = 6,
                            TenPhongBan = "Phòng Hành Chính"
                        });
                });

            modelBuilder.Entity("WebQLNhanSu.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<int?>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoans", t =>
                        {
                            t.HasCheckConstraint("CK_TK_VaiTro", "[VaiTro] IN ('Admin','HR','Employee')");
                        });

                    b.HasData(
                        new
                        {
                            MaTaiKhoan = 1,
                            MatKhau = "admin123",
                            TenDangNhap = "admin",
                            TrangThai = true,
                            VaiTro = "Admin"
                        },
                        new
                        {
                            MaTaiKhoan = 2,
                            MatKhau = "hr123",
                            TenDangNhap = "hr",
                            TrangThai = true,
                            VaiTro = "HR"
                        },
                        new
                        {
                            MaTaiKhoan = 3,
                            MatKhau = "employee123",
                            TenDangNhap = "employee",
                            TrangThai = true,
                            VaiTro = "Employee"
                        });
                });

            modelBuilder.Entity("WebQLNhanSu.Models.TrinhDo", b =>
                {
                    b.Property<int>("MaTrinhDo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTrinhDo"));

                    b.Property<string>("TenTrinhDo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaTrinhDo");

                    b.HasIndex("TenTrinhDo")
                        .IsUnique();

                    b.ToTable("TrinhDos");

                    b.HasData(
                        new
                        {
                            MaTrinhDo = 1,
                            TenTrinhDo = "Cao Đẳng"
                        },
                        new
                        {
                            MaTrinhDo = 2,
                            TenTrinhDo = "Đại Học"
                        },
                        new
                        {
                            MaTrinhDo = 3,
                            TenTrinhDo = "Thạc Sĩ"
                        },
                        new
                        {
                            MaTrinhDo = 4,
                            TenTrinhDo = "Tiến Sĩ"
                        },
                        new
                        {
                            MaTrinhDo = 5,
                            TenTrinhDo = "Không Có"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebQLNhanSu.Models.BangLuong", b =>
                {
                    b.HasOne("WebQLNhanSu.Models.NhanVien", "NhanVien")
                        .WithMany("BangLuongs")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("WebQLNhanSu.Models.ChamCong", b =>
                {
                    b.HasOne("WebQLNhanSu.Models.CaLamViec", "CaLamViec")
                        .WithMany("ChamCongs")
                        .HasForeignKey("MaCa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebQLNhanSu.Models.NhanVien", "NhanVien")
                        .WithMany("ChamCongs")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaLamViec");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("WebQLNhanSu.Models.HopDong", b =>
                {
                    b.HasOne("WebQLNhanSu.Models.LoaiHopDong", "LoaiHopDong")
                        .WithMany("HopDongs")
                        .HasForeignKey("MaLoaiHopDong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebQLNhanSu.Models.NhanVien", "NhanVien")
                        .WithMany("HopDongs")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiHopDong");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("WebQLNhanSu.Models.LichSuNguoiDung", b =>
                {
                    b.HasOne("WebQLNhanSu.Models.TaiKhoan", "TaiKhoan")
                        .WithMany("LichSuNguoiDungs")
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("WebQLNhanSu.Models.NghiPhep", b =>
                {
                    b.HasOne("WebQLNhanSu.Models.NhanVien", "NhanVien")
                        .WithMany("NghiPheps")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("WebQLNhanSu.Models.NhanVien", b =>
                {
                    b.HasOne("WebQLNhanSu.Models.ChucVu", "ChucVu")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaChucVu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebQLNhanSu.Models.PhongBan", "PhongBan")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaPhongBan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebQLNhanSu.Models.TrinhDo", "TrinhDo")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaTrinhDo")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ChucVu");

                    b.Navigation("PhongBan");

                    b.Navigation("TrinhDo");
                });

            modelBuilder.Entity("WebQLNhanSu.Models.TaiKhoan", b =>
                {
                    b.HasOne("WebQLNhanSu.Models.NhanVien", "NhanVien")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("WebQLNhanSu.Models.CaLamViec", b =>
                {
                    b.Navigation("ChamCongs");
                });

            modelBuilder.Entity("WebQLNhanSu.Models.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("WebQLNhanSu.Models.LoaiHopDong", b =>
                {
                    b.Navigation("HopDongs");
                });

            modelBuilder.Entity("WebQLNhanSu.Models.NhanVien", b =>
                {
                    b.Navigation("BangLuongs");

                    b.Navigation("ChamCongs");

                    b.Navigation("HopDongs");

                    b.Navigation("NghiPheps");

                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("WebQLNhanSu.Models.PhongBan", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("WebQLNhanSu.Models.TaiKhoan", b =>
                {
                    b.Navigation("LichSuNguoiDungs");
                });

            modelBuilder.Entity("WebQLNhanSu.Models.TrinhDo", b =>
                {
                    b.Navigation("NhanViens");
                });
#pragma warning restore 612, 618
        }
    }
}
